title = "Ryerson Bike Club"
baseurl = "https://ryersonbikes.com"
languageCode = "en-ca"
theme = "prologue"

[params]
	copyright = "Ryerson Bike Club 2017"

	[params.social.twitter]
	icon = "twitter"
	link = "http://twitter.com/ryersonbikes"