baseurl = "https://ryersonbikes.com"
languageCode = "en-us"
title = "Ryerson University Cycling Club"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
#disqusShortname = "spf13"
# Enable google analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"

[params]
    site_author = "RUCC"
    site_description = "RUCC - the hub for cycling in Toronto."
    location = "Toronto Ontario"
    # Link custom assets relative to /static
    avatar = "img/avatar.gif"
    header_background = "img/banner.jpg"
    header_title = "Welcome to the Ryerson University Cycling Club"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "RyersonBikes"
    facebook  = "RUCycling"
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = "ru.cycling"
    github    = ""
    gplus     = ""
