baseURL = "https://ryersonbikes.com"
languageCode = "en-us"
title = "Ryerson University Cycling Club"
#themesDir = "../.."
theme = "hugo-serif-theme"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = "UA-155328917-1"
  # google_tag_manager_id = ""

  [params.logo]
    mobile = "img/RUCC Logo 2020 - square.png"
    standard  = "img/RUCC logo horizontal.png"
    alt = "RUCC"

  [params.homepage_meta_tags]
    meta_description = "Ryerson University Cycling Club is Ryerson's only club focused on Biking Culture and Rides."
    meta_og_title = "Ryerson University Cycling Club"
    meta_og_type = "website"
    meta_og_url = "www.ryersonbikes.com"
    # meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Ryerson University Cycling Club is Ryerson's only club focused on Biking Culture and Rides."
    meta_twitter_card = "summary"
    meta_twitter_site = "@ryersonbikes"
    meta_twitter_creator = "@luis_zugasti"

[menu]
  # Main Menu
  [[menu.main]]
    name = "Activities"
    url = "/activities/"
      weight = 1

  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 2
	 
  [[menu.main]]
      name = "Resources"
      url = "/resources/"
      weight = 3

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 4

  [[menu.main]]
      name = "FAQ"
      url = "/faq/"
      weight = 5  
	  
  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
