baseURL = "www.ryersonbikes.com"
languageCode = "en-us"
title = "Ryerson University Cycling Club"
#themesDir = "../.."
theme = "hugo-serif-theme"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  # google_analytics_id = ""
  # google_tag_manager_id = ""

  [params.logo]
    # mobile = "images/logo-mobile.svg"
    # standard  = "images/logo.svg"
    # alt = "Serif - A Hugo Business Theme"

  [params.homepage_meta_tags]
    meta_description = "Ryerson University Cycling Club is Ryerson's only club focused on Biking Culture and Rides."
    meta_og_title = "Ryerson University Cycling Club"
    meta_og_type = "website"
    meta_og_url = "www.ryersonbikes.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Ryerson University Cycling Club is Ryerson's only club focused on Biking Culture and Rides."
    meta_twitter_card = "summary"
    meta_twitter_site = "@ryersonbikes"
    meta_twitter_creator = "@zerostaticio"

[menu]
  # Main Menu
  [[menu.main]]
    name = "Routes"
    url = "/routes/"
      weight = 1

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 2
	 
  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 3

  [[menu.main]]
      name = "Contact"
      url = "/Contact/"
      weight = 4  
	  
  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
